export const SEARCH_REPO_REQUEST = 'SEARCH_REPO_REQUEST';
export const SEARCH_REPO_SUCCESS = 'SEARCH_REPO_SUCCESS';
export const SEARCH_REPO_ERROR= 'SEARCH_REPO_ERROR';

export const GET_REPO_REQUEST = 'GET_REPO_REQUEST';
export const GET_REPO_SUCCESS = 'GET_REPO_SUCCESS';
export const GET_REPO_ERROR= 'GET_REPO_ERROR';